"""add auth_cookie to domains

Revision ID: 56f270fd0d93
Revises: 15544c9ecca8
Create Date: 2026-07-25 06:21:48.704387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f270fd0d93'
down_revision: Union[str, None] = '15544c9ecca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('auth_cookie', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'auth_cookie')
    # ### end Alembic commands ###
